---
# Deploy app
- name: Create app directory
  file:
    path: "{{ app_dir }}"
    state: directory
  tags:
    - app

- name: Deploy app files
  synchronize:
    src: ../app/
    dest: "{{ app_dir }}"
    delete: yes
  tags:
    - app

- name: Configure Apache virtual host
  template:
    src: apache_app.conf.j2
    dest: "/etc/apache2/sites-available/{{ apache.server_name }}.conf"
    owner: root
    mode: "0644"
  notify: Restart Apache
  tags:
    - app

- name: Disable default virtual host
  command: a2dissite 000-default
  notify: Restart Apache
  tags:
    - app

- name: Enable new virtual host
  command: "a2ensite {{ apache.server_name }}"
  notify: Restart Apache
  tags:
    - app

# to restart apache
- name: Run handlers
  meta: flush_handlers
  tags:
    - app
    - system
