---
- name: Restart MySQL
  service: 
    name: mysql 
    state: restarted

- name: Restart Apache
  service: 
    name: apache2 
    state: restarted

- name: Restart CodeDeploy Agent
  service:
    name: codedeploy-agent
    state: restarted

- name: Reboot instance
  reboot:
    msg: Maintenance reboot initiated