---
- name: Install Monit
  apt:
    update_cache: yes
    state: present
    name: monit
  tags:
    - monit

- name: Configure Apache monitoring
  file:
    src: /etc/monit/conf-available/apache2
    dest: /etc/monit/conf-enabled/apache2
    owner: root
    group: root
    state: link
  notify: Restart Monit
  tags:
    - monit

- name: Configure MySQL monitoring
  file:
    src: /etc/monit/conf-available/mysql
    dest: /etc/monit/conf-enabled/mysql
    owner: root
    group: root
    state: link
  notify: Restart Monit
  tags:
    - monit

- name: Start the Monit service
  service:
    name: monit
    state: started
    enabled: true
  tags:
    - monit
