---
# Set up MySQL
# See: 
# https://stackoverflow.com/questions/26597926/install-mysql-with-ansible-on-ubuntu
# https://serverfault.com/questions/891373/unable-to-create-mysql-database-through-ansible
- name: Copy MySQL root credentials as .my.cnf file
  template: 
    src: root_mysql_my.cnf.j2 
    dest: /root/.my.cnf 
    owner: root
    mode: '0600'
  tags:
    - mysql

- name: Install MySQL
  apt:
    state: present
    install_recommends: yes
    name:
      - mysql-client
      - mysql-server
      - python-pymysql
      - libmysqlclient-dev
  tags:
    - mysql

- name: Start the MySQL service
  service: 
    name: mysql 
    state: started
    enabled: true
  tags:
    - mysql

- name: Update MySQL root password for all root accounts
  mysql_user: 
    name: root 
    host: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    password: "{{ mysql.root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  notify:
    - Restart MySQL        
  tags:
    - mysql

- name: Ensure anonymous user(s) are not in the database
  mysql_user: 
    name: '' 
    host: "{{ item }}" 
    state: absent
  with_items:
    - localhost
    - "{{ ansible_hostname }}"
  notify:
    - Restart MySQL        
  tags:
    - mysql

- name: Remove the test database
  mysql_db: 
    name: test 
    state: absent
  notify:
    - Restart MySQL
  tags:
    - mysql

- name: Create app database
  mysql_db:
    name: "{{ mysql.database_name }}"
    state: present
    collation: utf8_general_ci
    encoding: utf8
  notify:
    - Restart MySQL
  tags:
    - mysql

- name: Create app database user
  mysql_user: 
    name: "{{ mysql.database_user }}" 
    password: "{{ mysql.user_password }}" 
    priv: "*.*:ALL" 
    host: localhost
  notify:
    - Restart MySQL        
  tags:
    - mysql

- name: Copy database dump files
  copy:
    src: "files/mysql/{{ mysql.database_dump }}"
    dest: "/tmp/{{ mysql.database_dump }}"
    owner: root
    group: root
    mode: '0644' 
  tags:
    - mysql

- name: Import database dump
  mysql_db:
    name: "{{ mysql.database_name }}"
    state: import
    target: "/tmp/{{ mysql.database_dump }}"
    login_host: localhost
    login_user: root
    login_password: "{{ mysql.root_password }}"
  when: import_db_dump is defined and import_db_dump == 'true'
  notify:
    - Restart MySQL        
  tags:
    - mysql