# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-syntax
version: 0.2

run-as: root

env:
  variables:
    HOST_ALIAS: ubuntu-1
    HOST_GROUP: web_servers
  parameter-store:
    CONFIG_BUCKET: /lightsail/config_bucket # config bucket 
    HOST_IP: /lightsail/host_ip # instance ip address
    KEY_NAME: /lightsail/key_name # name of instance ssh key

phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - chmod +x ./scripts/build.sh
      - ./scripts/build.sh
