#!/usr/bin/env ansible-playbook
---
- name: Configure LAMP stack
  hosts: all
  become: yes
  become_user: root
  vars_files:
    - vars/all/app_config.yml
    - vars/all/mysql_config.yml
    - vars/{{ env }}/aws_config.yml

  tasks:

    # Configure repositories
    - import_tasks: tasks/repositories.yml

    # System update
    - name: Upgrade system
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes
      tags:
        - system

    # Set up AWS CLI
    - import_role:
        name: aws_onpremises
      vars:
        aws_onpremises_access_key_id: "{{ aws.aws_access_key_id }}"
        aws_onpremises_secret_access_key: "{{ aws.aws_secret_access_key }}"
      tags:
        - aws_onpremises

    # Set up apache
    - import_tasks: tasks/apache.yml

    # Set up MySQL
    - import_tasks: tasks/mysql.yml

    - import_role:
        name: mysql_backup_s3
      vars:
        mysql_backup_username: root
        mysql_backup_bucket: "{{ aws.backup_bucket }}"
      tags:
        - mysql
        - mysql_backup_s3

    # Set up PHP
    - import_tasks: tasks/php.yml

    # Set up AWS CodeDeploy
    - import_role: 
        name: aws_codedeploy
      vars:
        aws_codedeploy_access_key_id: "{{ aws.aws_access_key_id }}"
        aws_codedeploy_secret_access_key: "{{ aws.aws_secret_access_key }}"
        aws_codedeploy_iam_user_arn: "{{ aws.iam_user_arn }}"
        aws_codedeploy_region: "{{ aws.region }}"
      tags:
        - aws_codedeploy

    # Deploy app
    - import_tasks: tasks/app.yml

    # Install and configure Let's Encrypt certificate in production
    - name: Install and configure Let's Encrypt certificate in production
      include_tasks: tasks/letsencrypt.yml
      when: env is defined and env == 'prod'
      tags:
        - letsencrypt

    # System check
    - name: Check if a reboot is required
      shell: "[ -f /var/run/reboot-required ]"
      failed_when: false
      register: reboot_required
      changed_when: reboot_required.rc == 0
      notify: Reboot instance
      tags:
        - system

  handlers:

    - import_tasks: tasks/handlers.yml 